### ISSUE TITLE
Is it possible to format Python code?

### ISSUE THREAD

**Issue by Ron-SK** [atom-ide-community/atom-ide-base#1]
Not sure if this is the right place to put this, but is it possible to format Python code using atom-ide-community?

**Comment by aminya** [comment]
Check https://atom.io/packages/atom-beautify!

**Comment by Ron-SK** [comment]
> Check https://atom.io/packages/atom-beautify!

Sure. Just curious though, would the ide-python package's built in formatting work (didn't work for me).

**Comment by aminya** [comment]
You should open an issue in its repository. https://github.com/lgeiger/ide-python. I cannot help here much.

**Comment by Ron-SK** [comment]
Sure.
